#!/bin/bash

# pacitude 2.0
# --------------------------------
# author    : Sachiko
#             https://github.com/undeadrevo
# project   : https://github.com/undeadrevo/pacitude
# license   : LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
#

apptitle="pacitude"


# --------------------------------------------------------
mainmenu(){
  if [ "$1" = "" ]; then
    nextitem="."
  else
    nextitem=$1
  fi
  options=()
  options+=("0)" "Update Mirror List")
  options+=("1)" "Sync DB")
  options+=("2)" "Update System")
  options+=("3)" "Install Packages")
  options+=("4)" "Remove Packages")
  options+=("5)" "Update Packages")
  options+=("6)" "Remove Dependencies")
  options+=("7)" "Search Packages")
  options+=("8)" "Belongs To Files")
  options+=("9)" "Package Info")
  options+=("10)" "Clear Cache")
  options+=("11)" "PacDiff Viewer")
  options+=("12)" "Edit pacman.conf")
  options+=("13)" "Edit mirrorlist")
  options+=("14)" "Pacman PGP Key Refresh")
  options+=("15)" "Pacman DB Optimize")
  options+=("16)" "Pacman DB Upgrade")
  options+=("17)" "Pacman Log")
  sel=$(whiptail --backtitle "$apptitle" --menu "" --cancel-button "$txtexit" --default-item "$nextitem" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ "$?" = "0" ]; then
    case $sel in
      "0)")
        sudo reflector -l 5 -p http --save /etc/pacman.d/mirrorlist
      ;;
      "1)")
        pacaur -Sy
      ;;
      "2)")
		    pacaur -Su
      ;;
      "3)")
		  pkgs=$(whiptail --backtitle "$apptitle" --title "Choose package(s) to install" --inputbox "" 0 0 "" 3>&1 1>&2 2>&3)
		  if [ "$?" = "0" ]; then
    	  clear
    	  pacaur -S $pkgs
 		  fi
 	  ;;
      "4)")
		  pkgs=$(whiptail --backtitle "$apptitle" --title "Choose package(s) to remove" --inputbox "" 0 0 "" 3>&1 1>&2 2>&3)
		  if [ "$?" = "0" ]; then
    	  clear
    	  pacaur -R $pkgs
 		  fi
      ;;
      "5)")
      	  pkgs=$(whiptail --backtitle "$apptitle" --title "Choose Package to update(exact filepath)" --inputbox "" 0 0 "" 3>&1 1>&2 2>&3)
		  if [ "$?" = "0" ]; then
    	  clear
    	  pacaur -U $pkgs
    	  fi
      ;;
      "6)")
		  if [ "$?" = "0" ]; then
		  clear
          pacaur -R $(pacaur -Qdtq)
      	  fi
      ;;
      "7)")
		  pkgs=$(whiptail --backtitle "$apptitle" --title "Choose package(s) to search for" --inputbox "" 0 0 "" 3>&1 1>&2 2>&3)
		  if [ "$?" = "0" ]; then
    	  clear
    	  pacaur -Ss $pkgs
        pressanykey
   		  fi
      ;;
      "8)")
		  pkgs=$(whiptail --backtitle "$apptitle" --title "" --inputbox "" 0 0 "" 3>&1 1>&2 2>&3)
		  if [ "$?" = "0" ]; then
    	  clear
    	  pacaur -Qo $pkgs
    	  fi
      ;;
      "9)")
		  pkgs=$(whiptail --backtitle "$apptitle" --title "Package Info" --inputbox "" 0 0 "" 3>&1 1>&2 2>&3)
		  if [ "$?" = "0" ]; then
    	  clear
    	  pacaur -Qi $pkgs
    	  fi
      ;;
      "10)")
    	  pacaur -Scc
      ;;
      "11)")
		  pkgs=$(whiptail --backtitle "$apptitle" --title "" --inputbox "" 0 0 "" 3>&1 1>&2 2>&3)
		  if [ "$?" = "0" ]; then
    	  clear
    	  pacaur -Qo $pkgs
    	  fi
      ;;
      "12)")
		  chooseeditor
		  sudo $EDITOR /etc/pacman.conf
      ;;
      "13)")
		  chooseeditor
		  sudo $EDITOR /etc/pacman.d/mirrorlist
	  ;;
	  "14)")
		  sudo pacman-key --refresh
	  ;;
	  "15)")
		  sudo pacman-optimize
	  ;;
	  "16)")
		  sudo pacman-db-upgrade 
	  ;;
	  "17)")
		  chooselogviewer
		  $VIEWER /var/log/pacman.log
	  ;;
    esac
    mainmenu "$nextitem"
  else
    clear
  fi
}

#-----------------------------------------------------------

chooseeditor(){
  options=()
  options+=("kilo" "")
  options+=("nano" "")
  options+=("pico" "")
  options+=("vi" "")
  options+=("vim" "")
  options+=("edit" "")
  sel=$(whiptail --backtitle "$apptitle" --title "Choose an editor" --menu "" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ "$?" = "0" ]; then
    clear
    echo "export EDITOR=$sel"
    export EDITOR=$sel
    EDITOR=$sel
    pressanykey
  fi
}

#--------------------------------------------------------------

chooselogviewer(){
  options=()
  options+=("more" "")
  options+=("cat" "")
  options+=("less" "")
  sel=$(whiptail --backtitle "$apptitle" --title "Choose a log viewer" --menu "" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ "$?" = "0" ]; then
    clear
    echo "export VIEWER=$sel"
    export VIEWER=$sel
    VIEWER=$sel
    pressanykey
  fi
}

#--------------------------------------------------------
pressanykey(){
  echo -e "\033[1;33m"
  read -n1 -p "$txtpressanykey"
  echo -e "\033[0m"
}

loadstrings(){
  txtexit="Exit"
  txtmainmenu="Main Menu"
  txtpressanykey="Press any key to continue."
}

# --------------------------------------------------------
  loadstrings
  EDITOR=nano
  mainmenu

exit 0
# --------------------------------------------------------