#!/bin/bash
#                                /$$   /$$                     /$$          
#                               |__/  | $$                    | $$          
#   /$$$$$$   /$$$$$$   /$$$$$$$ /$$ /$$$$$$   /$$   /$$  /$$$$$$$  /$$$$$$ 
#  /$$__  $$ |____  $$ /$$_____/| $$|_  $$_/  | $$  | $$ /$$__  $$ /$$__  $$
# | $$  \ $$  /$$$$$$$| $$      | $$  | $$    | $$  | $$| $$  | $$| $$$$$$$$
# | $$  | $$ /$$__  $$| $$      | $$  | $$ /$$| $$  | $$| $$  | $$| $$_____/
# | $$$$$$$/|  $$$$$$$|  $$$$$$$| $$  |  $$$$/|  $$$$$$/|  $$$$$$$|  $$$$$$$
# | $$____/  \_______/ \_______/|__/   \___/   \______/  \_______/ \_______/
# | $$                                                                      
# | $$                                                                      
# |__/                                                                      
#
#
# A pacman and pacaur wrapper with apt inspired syntax


SYNTAX=$1
INPUT=$2

case "$SYNTAX" in
        install)
                pacaur -S "$INPUT"
                ;;
        search)
                pacaur -Ss "$INPUT"
                ;;
        remove)
                pacaur -Rs "$INPUT"
                ;;
        upgrade)
                pacaur -Su
                ;;
        update)
                pacaur -Sy
                ;;
        download)
                pacaur -Sw "$INPUT"
                ;;
        autoremove)
                pacaur -Qdtq | pacaur -Rs -
                ;;
        show)
                pacaur -Qi "$INPUT"
                ;;
        clean)
                printf "%s\n" $"cleaning pacman cache..."
                sleep 1s
                pacaur -Sc
                printf "%s\n" $"cleaning pacaur cache..."
                sleep 1s
                rm -rf "$HOME/.cache/pacaur/*"
                ;;
        policy)
                less /etc/pacman.d/mirrorlist
                ;;
        list)
                pacaur -Q
                ;;
        listm)
                pacaur -Qi
                ;;
        listl)
                pacaur -Q | wc -l
                ;;
        build)
                makepkg -sri
                ;;
        help)
                cat <<-EOF
	            pacitude - a pacaur wrapper with apt inspired syntax
                          help - print this help
                          install <package> - installs a package
                          search <package> - searches for a package in the repos
                          remove <package> - removes a package
                          upgrade - upgrades the system
                          update - only refreshes the repos (bad practice, do not run this without running 'upgrade' immediately after
                          download <package> - only download a package into pacman's cache without installing it
                          autoremove - remove dependencies that are no longer needed (usually should not be needed as 'remove' should remove dependencies along with the package)
                          show <package> - shows information about the package
                          clean - clears pacman and pacaur's caches
                          policy - prints mirrorlist
                          list - lists all installed packages
                          listm - lists all installed packages with all info
                          listl - lists how many packages are installed
                          build - builds package from PKGBUILD
EOF
                ;;
        *)
                printf "%s\n" $"Insufficient paramaters. Use 'pacitude help' for more info"
                ;;
esac